<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

</head>

<body>
    <div id="root"></div>
    <h3>错误边界无法捕获以下场景中产生的错误：

        事件处理（了解更多）
        异步代码（例如 setTimeout 或 requestAnimationFrame 回调函数）
        服务端渲染
        它自身抛出来的错误（并非它的子组件）
    </h3>
</body>
<script type="text/babel">
// 错误边界只针对 React 组件。只有 class 组件才可以成为错误边界组件。大多数情况下, 你只需要声明一次错误边界组件, 并在整个应用中使用它。
    class ErrorBoundary extends React.Component {
        constructor(props) {
            super(props);
            this.state = { error: null, errorInfo: null };
        }

        componentDidCatch(error, errorInfo) {
            // Catch errors in any components below and re-render with error message
            this.setState({
                error: error,
                errorInfo: errorInfo
            })
            // You can also log error messages to an error reporting service here
        }

        render() {
            if (this.state.errorInfo) {
                // Error path
                return (
                    <div>
                        <h2>Something went wrong.</h2>
                        <details style={{ whiteSpace: 'pre-wrap' }}>
                            {this.state.error && this.state.error.toString()}
                            <br />
                            {this.state.errorInfo.componentStack}
                        </details>
                    </div>
                );
            }
            // Normally, just render children
            // ================= 包裹作用  =====================
            return this.props.children;
        }
    }

    class BuggyCounter extends React.Component {
        constructor(props) {
            super(props);
            this.state = { counter: 0 };
            this.handleClick = this.handleClick.bind(this);
        }

        handleClick() {
            this.setState(({ counter }) => ({
                counter: counter + 1
            }));
        }

        render() {
            if (this.state.counter === 5) {
                // Simulate a JS error
                throw new Error('I crashed!');
            }
            return <h1 onClick={this.handleClick}>{this.state.counter}</h1>;
        }
    }

    function App() {
        return (
            <div>
                <p>
                    <b>
                        This is an example of error boundaries in React 16.
                        <br /><br />
                        Click on the numbers to increase the counters.
                        <br />
                        The counter is programmed to throw when it reaches 5. This simulates a JavaScript error in a component.
                    </b>
                </p>
                <hr />
                <ErrorBoundary>
                    <p>These two counters are inside the same error boundary. If one crashes, the error boundary will replace both of them.</p>
                    <BuggyCounter />
                    <BuggyCounter />
                </ErrorBoundary>
                <hr />
                <p>These two counters are each inside of their own error boundary. So if one crashes, the other is not affected.</p>
                <ErrorBoundary><BuggyCounter /></ErrorBoundary>
                <ErrorBoundary><BuggyCounter /></ErrorBoundary>
            </div>
        );
    }



    ReactDOM.render(
        <App />,
        document.getElementById('root')
    );

</script>

</html>